export const nome       = document.querySelector("#nome")
export const imagem     = document.querySelector("#imagem")
export const descricao  = document.querySelector("#descricao")
export const imgcard    = document.querySelector("#img001")
export const nomecard   = document.querySelector("#nomeCard")
export const desccard   = document.querySelector("#descCard")
export const botao      = document.querySelector("#btn1")
